### ISSUE TITLE
Some problems about multipointSparse

### ISSUE THREAD

**Issue by NWPU-XuChenzhou** [mdolab/adflow#10]
Good day, John.
Sorry for disturbing you. I'm a PhD student from NWPU. I have already installed "MDOlab code" you uploaded several days ago. These codes are really helpful for me. I followed MACH Tutorial to learn to use these codes. The example for ADflow analysis, illustrated in http://mdolab.engin.umich.edu/docs/packages/machtutorial/doc/aero_adflow.html, was tested successfully in my own PC. I used 1core and 4 cores to run aero_run.py respectively, and it appeared all right. However, when I ran aero_opt.py, some problems occurred. First, the multipoint package was not open source, so there was an error because the python script imported module multipoint.

xcz@ubuntu:~/Desktop/ADflow_test/opt_wing$ python aero_opt.py
Warning:` OpenMDAO dependency is not installed. OM_ADFLOW wrapper will not be active
Traceback (most recent call last):
File "aero_opt.py", line 14, in 
from multipoint import *
_No module named multipoint

For all the aero_opt or aerostruct_opt cases in the tutorial, the scripts import module multipoint. Hence, I commented out the lines with multipointSparse in aero_opt.py myself, and modified the script with no reference script. Then I got a problem with MPI erroror after ADflow finished in the process.

......
writetecplotsurfacesolution': True}
MPI_ABORT was invoked on rank 0 in communicator MPI_COMM_WORLD
with errorcode 1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.

[1]PETSC ERROR: ------------------------------------------------------------------------
[1]PETSC ERROR: Caught signal number 15 Terminate: Some process (or the batch system) has told this process to end
[1]PETSC ERROR: Try option -start_in_debugger or -on_error_attach_debugger
[1]PETSC ERROR: or see http://www.mcs.anl.gov/petsc/documentation/faq.html#valgrind
......

I have added my script in the attachment. Could you help me to modify my script? BTW, will the multipoint package be open source soon? Thanks a lot.

[aero_opt.py.txt](https://github.com/mdolab/adflow/files/3131633/aero_opt.py.txt)

[aero_opt.py.txt](https://github.com/mdolab/adflow/files/3131621/aero_opt.py.txt)

**Comment by GuardZ** [comment]
Try to reinstall your openmpi or change the version of openmpi. I think that there are still something wrong in your setting of openmpi or mpi4py.

**Comment by NWPU-XuChenzhou** [comment]
> Try to reinstall your openmpi or change the version of openmpi. I think that there are still something wrong in your setting of openmpi or mpi4py.

Thank you very much. Sorry for replying late. I have tested ADflow with an aerodynamic analysis case, as I metioned before, with 4 cores in my PC.  It performed well and finished correctly.
+-------------------------------------------------+
|
| Solution Timings:
|
| Set AeroProblem Time          :      0.003 sec
| Solution Time                 :    101.547 sec
| Write Solution Time           :      0.206 sec
| Stability Parameter Time      :      0.000 sec
|
| Total Call Time               :    101.756 sec
+--------------------------------------------------+
-> Alpha... 1.500000 
+---------------------------------------------------+
|
| Function Timings:
|
| Function AeroProblem Time     :      0.035 sec
| Function Evaluation Time      :      0.001 sec
| User Function Evaluation Time :      0.000 sec
|
| Total Function Evaluation Time:      0.036 sec
+--------------------------------------------------+
{'wing_cl': 0.41769439572452155, 'wing_cd': 0.016808170024248777}

So, if I have something wrong with my openmpi or mpi4py, will I get the above results with ADflow? I wonder if the  aerodynamic analysis case covered up the problems in my openmpi or mpi4py. I followed the installation instructions in the website when I installed opemmpi and mpi4py. In aero_opt.py.txt, the python script with mpi problem, I commented out the lines with multipointSparse. Hence, there maybe some problems for mpi interactions. Could you help me check it? Thanks a lot.

**Comment by NWPU-XuChenzhou** [comment]
> Try to reinstall your openmpi or change the version of openmpi. I think that there are still something wrong in your setting of openmpi or mpi4py.

Sorry, I made a mistake that I attached a unmodified script `aero_opt.py` , which is the example python scriot you gave in the tutorial.  I have modified it by commenting out the lines with multipointSparse and renamed it as `sing_aero_opt.py`. Could you help me check it? Sorry again for my carelessness.
[single_aero_opt.py.txt](https://github.com/mdolab/adflow/files/3145060/single_aero_opt.py.txt)

**Comment by joanibal** [comment]
Hey,

We decided to opensource [mutipoint](https://github.com/mdolab/multipoint) as well.
This should hopefully make things a little easier for you.

**Comment by NWPU-XuChenzhou** [comment]
> Hey,
> 
> We decided to opensource [mutipoint](https://github.com/mdolab/multipoint) as well.
> This should hopefully make things a little easier for you.

Your support is greatly appreciated. Thank you very much.  I'll try this.
