### ISSUE TITLE
How to change  coordinates the in ADflow?

### ISSUE THREAD

**Issue by NWPU-XuChenzhou** [mdolab/adflow#11]
Good day. 
Sorry for disturbing you. I have already installed ADflow, and want to run CRM wing case. In the gird  `Baseline 3M grid in block-structured CGNS format` I download from MDOlab web, wing span is in y direction. For ADflow, is the defult coordinate for wing span is z axis? If so, how should I set parameter in aero_run.py to rotate the calculation axises?

I found some pecifics in tutorial , and I'm not sure if this is axis definition?
![image](https://user-images.githubusercontent.com/37506048/57759156-ee7d5100-772b-11e9-9afd-4753969db8cb.png)

Thanks a lot.

**Comment by GuardZ** [comment]
Well, you can use option `liftIndex` to specify the coordinate index that will be considered the 'lift' direction.
2 for the y-axis as the lift direction and 3 for the z-axis as the lift direction.

**Comment by NWPU-XuChenzhou** [comment]
> Well, you can use option `liftIndex` to specify the coordinate index that will be considered the 'lift' direction.
> 2 for the y-axis as the lift direction and 3 for the z-axis as the lift direction.

Thank you very much. I found the  'liftIndex' in the option list and I will try this. Thanks again.

**Comment by NWPU-XuChenzhou** [comment]
> Well, you can use option `liftIndex` to specify the coordinate index that will be considered the 'lift' direction.
> 2 for the y-axis as the lift direction and 3 for the z-axis as the lift direction.
I have another problem about DVConstraints. I define geometric constraints(including volume and thickness constraints) for CRM wing optimization case and a problem occurred:
![image](https://user-images.githubusercontent.com/37506048/57760973-276af500-772f-11e9-9b72-a8e96eac5761.png)
I wonder if this means that the points I define for LE/TE list  lie outside the wing or their connection lines have some positions outside the surface of the wing.
Thank you.

**Comment by gkenway** [comment]
Yes that means there node wasn't projected correctly. Make sure that node you are projected is inside the wing. Another gotcha is that the *normal* is such that the projection just misses the surface, this can happen at a symmetry plane if the surface from which the Le/Te list is defined is not exactly planar.
