### ISSUE TITLE
Re-generating differentiated code using latest version of Tapenade (3.16)

### ISSUE THREAD

**Issue by garobed1** [mdolab/adflow#120]
I'm trying to differentiate some of the relevant residual routines with respect to the Spalart-Allmaras model constants, although this issue is not specific to that application. I installed the latest version of Tapenade (3.16), and following the instructions in the documentation for adflow, I was able to successfully generate the differentiated code that I need.

However, I noticed that the current differentiated code was generated using Tapenade v3.10. The newly generated code's files are all named differently, e.g. in `/adflow/src/adjoint/outputForward/`

`sa_b.f90` (3.10)
`sa.F90_b.f90` (3.16)

and the new version appends `iff` to some modules in `use` by the differentiated routines, e.g.

`use blockpointers` (3.10)
`use blockpointersiff` (3.16)

but `blockpointersiff` doesn't exist. From my perspective, I could try going through the newly-generated code manually and copying the relevant lines to the old formatted differentiated code. I have been trying to build the older version of Tapenade on my system as well, but have had difficulties doing so. I'm curious as to what the best approach to this problem would be for me at the moment, whether I should focus on building the older version of Tapenade or retool the existing differentiated files manually.

**Comment by anilyil** [comment]
The instructions will only work if you use the same version of tapenade. If you want to use the latest version, you will need to update the tapenade commands to generate consistent AD code and verify that the new code also runs correctly. Furthermore, you should not make any manual modifications to the tapenade generated code.

**Comment by gyzhangqm** [comment]
@garobed1 
The module name with "_DIFF" can be changed to "_b" with Tapenade3.16  command-line options:  -adjmodulename "_b".

And the generated file name can be solved with a line in autoEdit*.py:
f = f.replace('.F90_d.f90', '_d.F90')

But the better way is to keep Tapenade version same with the developer.
Could you transfer to me a copy of the old Tapenade binaries for version 3.10?
thx.
