### ISSUE TITLE
Tapenade 3.10 binaries fail

### ISSUE THREAD

**Issue by garobed1** [mdolab/adflow#124]
I hesitate to bring a Tapenade-specific issue up here, but since I need to use the older version 3.10 to generate differentiated code in ADflow and the developers of Tapenade do not necessarily want to support older versions, I will make one. Feel free to close this if this is appropriate.

I had originally wanted to use Tapenade to differentiate some RANS residuals with respect to the Spalart-Allmaras model parameters. I was successful using the latest version of Tapenade (3.16), but there are certain formatting differences in that version that prevent the code from compiling with ADflow. @joanibal provided me with the old Tapenade binaries for version 3.10, but I have been unable to use those binaries to generate _any_ differentiated code. Regardless of whether I try differentiating my modified ADflow branch, the original unaltered ADflow, or even the tutorial example in Tapenade's user guide (https://tapenade.gitlabpages.inria.fr/userdoc/build/html/tapenade/tutorial.html), I hit the same error as below:

```
File: /home/garobed/tapenade3.10/bin/linux/fortranParser: 1: /home/garobed/tapenade3.10/bin/linux/fortranParser: Syntax error: "(" unexpected
System: Parsing error in ../adjoint/adjointExtra.F90.f90
System: Parsing error in ../modules/surfaceFamilies.F90.f90
System: Parsing error in ../modules/monitor.f90.f90
System: Parsing error in ../modules/diffSizes.f90.f90
```

So far, I have tried messing with some of the environment variables that the `tapenade` script uses, e.g. `HEAP_SIZE=-mx2048m`, to no effect. I am using the latest version of the Java development kit as well; an older version might be needed to work. I'll look into different Java versions, but if anyone has seen this issue using Tapenade 3.10, I would appreciate any help.

**Comment by eirikurj** [comment]
The issue that is showing up seems to be a syntax related one. Are you running this on a clean cloned ADflow repo, i.e., not on your modified source code?. I suggest you try that first if you have not already.

Which JRE are you using? We have had issues with the JRE in the past and have depended on specific versions for it. I suggest you use JRE 8 (most recent security patches should work). For instance update 281 should work as well as an older update 60. You can download the most recent one here https://www.java.com/en/download/. Also, I suggest you add something like the following to your `.bashrc` for convenience.
```
# Tapenade
export PATH=$HOME/packages/tapenade3.10/bin:$PATH
# Java
export PATH=$HOME/packages/jre1.8.0_281/bin:$PATH
```

Finally, please continue to bring up any issues, feature request, or code improvements, but also understand we have limited resources to act on these. Also, keep in mind you can always make those changes and submit a PR.

**Comment by garobed1** [comment]
Unfortunately, I haven't had much luck getting it to work on my current machine. I resorted to using Tapenade 3.10 on another machine, however, which worked. For reference, this other (working) machine uses Java 1.8.0_275 Linux, while the original (not working) machine uses Java 1.8.0_282 Linux. I'll close the issue as I've essentially found a solution.

**Comment by gyzhangqm** [comment]
@garobed1 

Could you transfer to me a copy of the old Tapenade binaries for version 3.10?
I met the same problem as you with Tapenade 3.16.

thx.

**Comment by gyzhangqm** [comment]
Tapenade cannot work with WSL. Your are right to do AD work with a pure linux machine.
