### ISSUE TITLE
Better error handling during setup

### ISSUE THREAD

**Issue by nwu63** [mdolab/adflow#146]
# Description of feature
Currently, if something fails during setup, we get the normal error message, but some other stuff is printed as well:
```
+------------------------------------------------------------------------------+
| Error: Datatype for option ANKCFLFactor is not valid. Expected data type     |
| <class 'float'>. Received data type is <class 'int'>.                        |
+------------------------------------------------------------------------------+

Exception ignored in: <function ADFLOW.__del__ at 0x7fa2b4c7bee0>
Traceback (most recent call last):
  File "...adflow/adflow/pyADflow.py", line 360, in __del__
    self.releaseAdjointMemory()
  File ".../adflow/adflow/pyADflow.py", line 3344, in releaseAdjointMemory
    if self.adjointSetup:
AttributeError: 'ADFLOW' object has no attribute 'adjointSetup'
```

# Potential solution
I'm guessing this is because the error occurred before the ADFLOW object was created. The `__del__` method probably needs to be updated to check for the attribute or something.

**Comment by joanibal** [comment]
The method already checks for the flag, but the flag is created later in the `__init__` :man_facepalming: . We should probably move the allocation related flags to the very top. 

This would be a good first issue for someone

**Comment by yasuomaidana** [comment]
There is a way to induce this error?

**Comment by nwu63** [comment]
Yeah, the error message above was generated by running ADflow with `ANKCFLFactor` set to an integer, which causes `baseclasses` to throw essentially a type error.

**Comment by awccopp** [comment]
I encountered this error message today. I can try to fix it.

**Comment by marcomangano** [comment]
@awccopp any chance you looked into this bugfix recently?

**Comment by awccopp** [comment]
I fixed this bug in particular related to the adjointSetup but now the deconstructor is having PETSc issues related to deallocating some arrays. Not sure how to fix those bugs.

**Comment by awccopp** [comment]
Nope but I can push it up now. I also fixed some issues with FORTRAN deallocation

**Comment by awccopp** [comment]
The changes I've made are available on my branch [here](https://github.com/awccopp/adflow/tree/error_fix)

**Comment by nwu63** [comment]
Can you share the test case to replicate the error?
