### ISSUE TITLE
run_reg_tests.py fails

### ISSUE THREAD

**Issue by Jethro-Moses** [mdolab/adflow#16]
I've managed to install ADflow with all the necessary prerequisite modules. However, I get the following message towards the end when I run make in my terminal.

Testing if module libadflow can be imported...
Module libadflow was successfully imported.

Note, it says libadflow instead of just adflow. Not sure if this is OK. I ran the run run_reg_tests.py script in python/reg_tests/ folder and I get the following errors

Error: number of @value lines in file not the same!
adflow test1: Failure!
Error: number of @value lines in file not the same!
adflow test2: Failure!
Error: number of @value lines in file not the same!
adflow test3: Failure!
Error: number of @value lines in file not the same!
adflow test4: Failure!
Error: number of @value lines in file not the same!
adflow test5: Failure!
Error: number of @value lines in file not the same!
adflow test6: Failure!
Error: number of @value lines in file not the same!
adflow test7: Failure!
Error: number of @value lines in file not the same!
adflow test8: Failure!
Error: number of @value lines in file not the same!
adflow test9: Failure!
Error: number of @value lines in file not the same!
adflow test10: Failure!
Error: number of @value lines in file not the same!
adflow test11: Failure!
Error: number of @value lines in file not the same!
adflow test12: Failure!
Error: number of @value lines in file not the same!
adflow test13: Failure!
Error: number of @value lines in file not the same!
adflow test14: Failure!
Error: number of @value lines in file not the same!
adflow test15: Failure!
Error: number of @value lines in file not the same!
adflow test16: Failure!
Error: number of @value lines in file not the same!
adflow test17: Failure!
Error: number of @value lines in file not the same!
adflow test18: Failure!

Thanks for your help.

**Comment by GodotMisogi** [comment]
Execute it with some of the options, e.g. `python run_reg_tests.py --test 1`.
