### ISSUE TITLE
Span function is incorrect in adjoint tests

### ISSUE THREAD

**Issue by sseraj** [mdolab/adflow#163]
## Description

The span function in test_adjoint.py is incorrect: https://github.com/mdolab/adflow/blob/9284f5216bf208b941d40cf136f9f488d7df1bff/tests/reg_tests/test_adjoint.py#L54-L59

This should be replaced with
```
def span(val, geo):

    C = geo.extractCoef("wing")
    s = geo.extractS("wing")

    for i in range(len(C)):
        C[i, 2] += s[i] * val[0]

    geo.restoreCoef(C, "wing")
```
and the tests should be retrained.

**Comment by nwu63** [comment]
Closed by #165.
