### ISSUE TITLE
Knowledge of internal nodes numbering (surfaces)

### ISSUE THREAD

**Issue by pedrobritotucano** [mdolab/adflow#172]
Hello,

We are using ADflow but inserting our own RHS for adjoint.
However, we need to know how internal nodes are numbered (index of the nodes for the surfaces) to input the external computed conditions (RHS) to the correct nodes. 

Is there a way of knowing this information in Adflow?
Can someone give me suggestions of how I can do/know that?

Regards, 
Brito.

**Comment by joanibal** [comment]
Hi Brito, 

Unfortunately this will be some what tricky. 
The ordering to the residuals is given by this loop.
https://github.com/mdolab/adflow/blob/f999afc681fb8f411d6c87e94045c79999e09919/src/NKSolver/NKSolvers.F90#L1432-L1447
The RHS you add should have the same ordering. 

I'm not sure about what you mean by the "index of the nodes for the surfaces". 
Could you provide more detail about what you are trying to do?
