### ISSUE TITLE
Segfault due to #158

### ISSUE THREAD

**Issue by nwu63** [mdolab/adflow#181]
## Description
I started getting segfaults recently in an aerostructural optimization script, and I used `git bisect` to trace it to #158. Unfortunately, I'm not able to reproduce this issue in the simple analysis case in MACH-Aero, but this is the log:

```
At line 1923 of file ../output/outputMod.F90
Fortran runtime error: Index '1' of dimension 1 of array 'viscpointer' below lower bound of 2
```
which corresponds to the line
```
mm = viscPointer(ii,jj)
```

Not entirely sure what the call graph here is, but it's happening at some point when writing the surface CGNS solution.

### Steps to reproduce issue
Haven't been able to reproduce this, but can help run cases and debug.

### Current behavior
There's a segfault

### Expected behavior
There shouldn't be a segfault

### Code versions

- Operating System: 
- Python: 
- OpenMPI: 
- CGNS: 
- PETSc: 
- This software: master branch

**Comment by joanibal** [comment]
Hmm, are you able to share the mesh you used?

Could you post your `surfacevariables`?

**Comment by nwu63** [comment]
```
"surfaceVariables": ["cp", "vx", "vy", "vz", "yplus", "sepsensor"]
"isosurface": {"shock": 1.0, "vx": -0.001},
```
Let's talk offline regarding the mesh.
