### ISSUE TITLE
segfault when writing cgns surface solutions that include  yplus in the surfacevariables list on pleiades.

### ISSUE THREAD

**Issue by anilyil** [mdolab/adflow#183]
## Description
The adflow build on the new operating system on pleiades segfaults when writing the cgns surface output file, but only when the variable `yplus` is included in the `surfacevariables` option. I can only recreate this issue with the podded fan overset mesh, and it does not show up with the mach-tutorial wing case. 

With the aeroprop case, the issue is there even on a single node, including a 1 proc run and a saturated node run. Its also there with a 4 node job with saturated nodes. 

One day before this, the tecplot surface output was also broken but it mysteriously fixed itself after a re-make of adflow. 

### Steps to reproduce issue

1. On pleiades, run any of the aeroprop benchmark cases with yplus in the surface variables list and write a cgns surface output.

### Current behavior
segfault

### Expected behavior
no segfault

### Code versions
- Operating System: TOSS 3
- Python: 3.9.5
- CGNS: 4.2.0 (also there with 4.1.2)
- PETSc: 3.15.4
- This software: https://github.com/mdolab/adflow/commit/d17ca9ffc33392c17533ed6d83dd056962b1c741
```
Currently Loaded Modulefiles:
  1) pkgsrc/2021Q2           2) comp-intel/2020.4.304   3) mpi-intel/2019.5.281    4) gcc/9.3                 5) python3/3.9.5
```

**Comment by nwu63** [comment]
_probably_ a duplicate of #181, since `yplus` is in the surface variables there also. I also could not reproduce this with MACH-Aero, it came up in a relatively large multiblock mesh for me.

**Comment by anilyil** [comment]
I am not getting the same runtime error but yeah they could be the same issue. Can you try without the yplus output?

**Comment by nwu63** [comment]
I can confirm that without `yplus` I do not get the segfault.

**Comment by anilyil** [comment]
definitely sounds like a duplicate of #181. Closing this since your issue has more detailed info
