### ISSUE TITLE
Finite Difference test for Adjoint Validation

### ISSUE THREAD

**Issue by Mohammad-Moniri** [mdolab/adflow#184]
Hello,
I am currently using ADFlow to solve an Adjoint problem with an arbitrary RHS and objective function.
To validate sensitivities, I want to perform a Finite Difference test. For this, what I need is "Cp" for each perturbed FD case ( then I will use Cp in our codes for our purpose). 
I wanted to see if there is any internal option in ADFlow to perform Finite Difference test (by moving mesh etc).
The current approach that I am taking is to create the mesh for disturbed geometry using "construc2D" code. But, "consructed2D" is single precision (I think) so I'm afraid that I will lose accuracy for FD test.
Thanks in advance,

**Comment by anilyil** [comment]
Sorry, we cannot provide support other than whats in the tutorials. Feel free to check https://github.com/mdolab/MACH-Aero

**Comment by joanibal** [comment]
Check out the tests for idea's about how to set up your [own FD tests of the fwd AD](https://github.com/mdolab/adflow/blob/d17ca9ffc33392c17533ed6d83dd056962b1c741/tests/reg_tests/test_jacVecProdFWD.py#L121-L123) or complex step tests to verify the accuracy of the adjoint (https://github.com/mdolab/adflow/blob/d17ca9ffc33392c17533ed6d83dd056962b1c741/tests/reg_tests/test_adjoint.py#L237)

I'm not sure what "construc2D" codes is, but your best bet for adding perturbations to the mesh is probably using `setSurfaceCoordinates` and `setSurfaceCoordinates`.
