### ISSUE TITLE
restartFile does not always work in parallel

### ISSUE THREAD

**Issue by sseraj** [mdolab/adflow#199]
## Description

Using the `restartFile` option with overset meshes in parallel can give the following error:

```
#--------------------------- !!! Error !!! ----------------------------
#* Terminate called by processor 0
#* Run-time error in procedure readRestartVariable
#* Error message: Something wrong when calling cg_field_read_f
#*
#* Now exiting
#----------------------------------------------------------------------
```
Whether or not this error occurs might depend on the mesh and the number of processors used.

This issue was previously noticed in #77. I don't think the bug was ever fixed, but the test changed to not use a restart file.

### Steps to reproduce issue

1. Add the following line to the options dictionary in `TestSolveOverset` in test_conic_conv_nozzle.py
```
"restartFile": os.path.join(baseDir, "../../input_files/conic_conv_nozzle.cgns"),
```

2. Try running the overset test on two processors:
```
mpiexec -np 2 python test_conic_conv_nozzle.py TestSolveOverset.test_solve
```

### Current behavior
ADflow crashes with the error above. With one processor, the test runs fine.

### Expected behavior
The test should run in parallel.

### Code versions

- CGNS: 4.2.0

**Comment by joanibal** [comment]
I'm trying to debug the same issue at the moment. 
But I am not using an overset mesh.

**Comment by joanibal** [comment]
I have been poking around in CGNS and I believe the issue has to do with block splitting and rind cells. At least for my case anyways.

**Comment by sseraj** [comment]
Interesting, I have not run into this with multiblock meshes. Is it just a parallel issue? I can update the issue title.

**Comment by joanibal** [comment]
I first encountered the issue when running in  parallel, but I can recreate the error when run with "partitionLikeNProc": 2,

**Comment by joanibal** [comment]
Here is basic example script to show the problem 
```python
import unittest
import os
from adflow import ADFLOW
from baseclasses import AeroProblem

baseDir = os.path.dirname(os.path.abspath(__file__))



gridFile = "input_files/mdo_tutorial_euler_scalar_jst.cgns"
options = {"gridfile": os.path.join(baseDir, "../../", gridFile),
            "restartFile" : os.path.join(baseDir, "../../", gridFile),
            "partitionLikeNProc": 20, 
            "MGCycle": "sg",
            "printIntro": False,
            "printAllOptions": False,
            "equationType": "Euler",
    
    }
ap_tutorial_wing = AeroProblem(
    name="mdo_tutorial",
    alpha=1.8,
    mach=0.80,
    P=20000.0,
    T=220.0,
    areaRef=45.5,
    chordRef=3.25,
    beta=0.0,
    R=287.87,
    xRef=0.0,
    yRef=0.0,
    zRef=0.0,
)

CFDSolver = ADFLOW(options=options, debug=False)

print("===========================================================")
print(CFDSolver.getResidual(ap_tutorial_wing))

```


Which will fail with the following error when `partitionLikeNProc` is greater than 14

```
#
#--------------------------- !!! Error !!! ----------------------------
#* Terminate called by processor 0
#* Run-time error in procedure readRestartVariable
#* Error message: Something wrong when calling cg_field_read_f
#*
#* Now exiting
#----------------------------------------------------------------------
#
#
#--------------------------- !!! Error !!! ----------------------------
#* Terminate called by processor 0
#* Run-time error in procedure readRestartVariable
#* Error message: Something wrong when calling cg_field_read_f
#*
#* Now exiting
#----------------------------------------------------------------------
##
#--------------------------- !!! Error !!! ----------------------------
#* Terminate called by processor 0
#* Run-time error in procedure readRestartVariable
#* Error message: Something wrong when calling cg_field_read_f
#*
#* Now exiting
#----------------------------------------------------------------------
```

**Comment by sseraj** [comment]
Thanks for adding the example! I can confirm that this reproduces the error.

**Comment by joanibal** [comment]
I traced the error back to this part in CGNS
https://github.com/CGNS/CGNS/blob/55afcfec8a0c9503dfead89c3cec477283e4fc5a/src/cgns_internals.c#L9401-L9418

The comment there seems to indicate that there was a change in behavior after CGNS 3.4

**Comment by joanibal** [comment]
OK I think I know how to fix this. I'll post a PR soon
