### ISSUE TITLE
Documenting additional python imports 

### ISSUE THREAD

**Issue by anilyil** [mdolab/adflow#205]
Using an issue to keep track of the additional imports I find throughout the adflow repo: 

- The OpenMDAO imports in https://github.com/mdolab/adflow/blob/main/adflow/om_adflow.py and related files will be removed in #196. The new implementation of the OpenMDAO wrappers will only import OpenMDAO if the wrapper itself is imported, instead of importing it any time ADflow is imported. 
- Scipy's KDTree is imported in the `setDisplacements` method in pyADflow
- https://github.com/mdolab/adflow/blob/main/adflow/pyWeightAndBalance.py imports `mdo_import_helper` (https://github.com/mdolab/adflow/blob/main/adflow/pyWeightAndBalance.py#L38) and `pyGeometry_complex` (https://github.com/mdolab/adflow/blob/main/adflow/pyWeightAndBalance.py#L43). There are possibly other imports through the `mdo_import_helper' (https://github.com/mdolab/adflow/blob/main/adflow/pyWeightAndBalance.py#L40-L41). This functionality most likely does not work right now. 
- https://github.com/mdolab/adflow/blob/main/adflow/pyWingCG.py imports `mdo_import_helper` similar to the pyWeightAndBalance.py file (https://github.com/mdolab/adflow/blob/main/adflow/pyWingCG.py#L38). Import helper is used to import other stuff. Likely does not work and not used currently.
- https://github.com/mdolab/adflow/blob/main/doc/conf.py imports the `sphinx_mdolab_theme` to build the documentation (https://github.com/mdolab/adflow/blob/main/doc/conf.py#L1)
- There are several additional imports in the test scripts. I will list them below and include links to one example for each import:
    1. `pyGeo` https://github.com/mdolab/adflow/blob/main/tests/reg_tests/test_adjoint.py#L11
    2. `pySpline` https://github.com/mdolab/adflow/blob/main/tests/reg_tests/test_adjoint.py#L12
    3. `IDWarp` https://github.com/mdolab/adflow/blob/main/tests/reg_tests/test_adjoint.py#L13

**Comment by nwu63** [comment]
Also, `petsc4py` is specified as a dependency but actually only PETSc is needed. Same thing happens in IDwarp.
