### ISSUE TITLE
Potential compilation issue with CGNS 3.4

### ISSUE THREAD

**Issue by smanist** [mdolab/adflow#25]
Just taking a note in case someone run into the same issue:

Recently I was compiling ADflow with the following dependencies under Ubuntu 18.04:
1. HDF5 1.10.3
2. CGNS 3.4 (shared, 64bit, fortran/hdf5/parallel-enabled)
3. PETSc 3.11 (takes care of HDF5)
4. Python 2.7/3.6

The Python import test fails by `undefined symbol: __cgns_MOD_bctypename` in Python 2.7, and seg fault in Python 3.6.

It turns out that the Fortran module from CGNS is not compiled correctly.  And one solution is available [here](https://cgnsorg.atlassian.net/browse/CGNS-118?page=com.atlassian.jira.plugin.system.issuetabpanels%3Aall-tabpanel)).  Near Line 551 of `./src/CMakeLists.txt`, one needs to change
```
add_library(cgns_shared SHARED ${cgns_FILES})
```
to
```
if (CGNS_ENABLE_FORTRAN)
    add_library(cgns_shared SHARED ${cgns_FILES} cgns_f.F90)
else (CGNS_ENABLE_FORTRAN)
    add_library(cgns_shared SHARED ${cgns_FILES})
endif (CGNS_ENABLE_FORTRAN)
```
Not sure if this bug has been fixed in the more recent CGNS 4.x version.

**Comment by anilyil** [comment]
thanks for creating this issue Daning. I think we will keep this open until we move to CGNS3.4. I think currently we are at 3.3.0.
