### ISSUE TITLE
Can't compile complex step within official docker image

### ISSUE THREAD

**Issue by DavidAnderegg** [mdolab/adflow#275]
## Description
Compiling for complex step within the official docker image `mdolab/public:u20-gcc-ompi-latest` fails with the following error:

```bash
...
        --- Compiled ALEUtils.F90 successfully ---

mpifort -fPIC -fdefault-real-8 -fdefault-double-8 -march=native -std=f2008  -I/home/mdolabuser/packages/CGNS-4.3.0/opt-gcc/include -I. -DUSE_COMPLEX -I/home/mdolabuser/packages/petsc-3.18.3/include -I/home/mdolabuser/packages/petsc-3.18.3/real-opt-gcc-3.18.3/include  -O3 -ffast-math -c ../utils/surfaceUtils.F90 -o surfaceUtils.o
../utils/surfaceUtils.F90:477:70:

  477 |                 call vecGetArrayF90(exch%nodeValLocal, localPtr, ierr)
      |                                                                      1
Error: Type mismatch in argument 'array' at (1); passed COMPLEX(8) to REAL(8)
...
```

### Steps to reproduce issue

1. update image `sudo docker image pull mdolab/public:u20-gcc-ompi-latest`
2. start it `sudo docker run -it --name test mdolab/public:u20-gcc-ompi-latest`
3. move to ADflow directory `cd repos/adflow/`
4. clean the CS files `make -f Makefile_CS clean`
5. Compile it `make -f Makefile_CS`

### Current behavior
It fails

### Expected behavior
It should compile

### Code versions
- repo: mdolab/public   
- tag: u20-gcc-ompi-latest   
- image-id: d2b777edf908   
- created: 4 hours ago

**Comment by eirikurj** [comment]
Please make sure to use a complex build of PETSc as well. Its already compiled on the docker images, so just running `export PETSC_ARCH=$PETSC_ARCH_COMPLEX` before running `make -f Makefile_CS`, should work.
You can do `make -f Makefile_CS PETSC_ARCH=$PETSC_ARCH_COMPLEX` if you dont want to update the env.
