### ISSUE TITLE
Update the adflow default options 

### ISSUE THREAD

**Issue by joanibal** [mdolab/adflow#34]
The default options for adflow are not up to date with recent development. 
I suggest that we examine the options and make a new set of defaults

Some changes I think should be made...
```python
'useank': True # it's been thoroughly vetted and is now a key feature of adflow
'useblockettes: False # This feature didn't get enough testing. We are still finding bugs with it. Its better used as something that can be turned on after it's known the optimization is working well.
'equationtype':'rans' # Most everyone uses adflow for rans nowadays 
```
What do you all think?

**Comment by anilyil** [comment]
The other thing that comes to my mind is 'nsubiterturb'. A higher than default value is needed to get decent performance from ANK but most people forget to set it.

**Comment by joanibal** [comment]
I'm going to bring this up at the next group meeting then plan on making the PR shortly after.

**Comment by camader** [comment]
we should probably add infChangeCorrection : True and remove rkreset

**Comment by anilyil** [comment]
nksolver is also turned off by default. if we turn it on by default, we probably should also change the default nkswitchtol from 2.5e-4 to something lower, around 1e-5.
