### ISSUE TITLE
Failure to assign multiple design surfaces

### ISSUE THREAD

**Issue by AbhijithMoni** [mdolab/adflow#344]
Hi,

I would like to report a bug in assigning multiple design surfaces to the **designSurfaceFamily** option.
```
 aero_options = {

    "designSurfaceFamily": "str",
}
```

In the options, there is only a possibility to assign either a string or None to the `designSurfaceFamily`  [source](https://mdolab-adflow.readthedocs-hosted.com/en/latest/options.html#designSurfaceFamily).  When I try to assign multiple surfaces I get an error which is expected based on the documentation (accepts only `str`). 
```
baseclasses.utils.error.Error:
 | Error: Datatype for option designSurfaceFamily is not valid. Expected data   |
| type (<class 'str'>, <class 'NoneType'>). Received data type is <class       |
| 'list'>
```

**Steps to reproduce issue**

In my CGNS multiblock mesh (Undeflected common research model), the wing geometry that I would like to optimize contains multiple components which consist of surfaces namely: `"wingu", "wingLE", "wingTE", "wingb"`. And `fuselage` and `tail` which are not a part of optimisation. 

Attempting to consolidate all wing surfaces into a "wing" family using `cgns_utils` proved challenging due to the inherent complexity of handling multiblock meshes.

Coraser version of the mesh is attached. 

[uCRM_coarse.zip](https://github.com/OpenMDAO/mphys/files/14142935/uCRM_coarse.zip)

**Code versions**

Docker image: mdolab/public:u18-gcc-ompi-latest

Thanks
Abhijith

**Comment by sseraj** [comment]
This is not a bug. Use [addFamilyGroup](https://mdolab-baseclasses.readthedocs-hosted.com/en/latest/pyAero_solver.html#baseclasses.AeroSolver.addFamilyGroup) to combine families into a group and use the group as the `designSurfaceFamily`.

**Comment by Yikun00** [comment]
Hello, I'm beginning to learn how to use this program for computing. Which platform is your computing grid generated from?

**Comment by Yikun00** [comment]
Hello, I'm just beginning to learn how to use this program for flow field calculations. Ask you what platform/grid software your computational grid is generated from?
