### ISSUE TITLE
Clean up obsolete forks

### ISSUE THREAD

**Issue by nwu63** [mdolab/adflow#42]
## Type of issue
What types of issue is it?
_Select the appropriate type(s) that describe this issue_

- Repo maintenance

This repository has many stale forks that have not been touched in years. Go through all the forks and delete those which are obsolete. If there's any useful code in the other forks, attempt to revive them, otherwise they should be thrown out too.

**Comment by anilyil** [comment]
@nwu63 I have deleted the obsolete branches. Can you verify if all looks good? 

I dont think there were any useful code in these branches. Only exception was the turbKSP branch, but I have it in my fork: https://github.com/anilyil/adflow/commits/turbKSP I doubt it has any code on top of master, but I was not sure. I will check at some point in my fork and create modifications as necessary.

**Comment by nwu63** [comment]
Everything looks fine, closing.
