### ISSUE TITLE
Document and update adflow options

### ISSUE THREAD

**Issue by eirikurj** [mdolab/adflow#43]
## Type of issue
- Documentation update

## Description
We need to put some effort into documenting all adflow options.
Current list https://mdolab-adflow.readthedocs-hosted.com/en/latest/options.html list is outdated and is missing many options.

## Preferred solution
This documentation should preferably be generated automatically. All options exist in `pyADflow.py` and default values etc. should be set from what is found there. The issue is with the detailed descriptions on what each parameter does. Either we can include a detailed description in `pyADflow.py`, or we can write them elsewhere and combine with an automated process.

**Comment by nwu63** [comment]
I figured out a way to do this via a custom Sphinx extension. See mdolab/pyoptsparse#130. To make this usable for many repos, we should package this, together with other docs/theme-related content such as the css override, into a repo and publish it on pyPI. Then, it can be pip-installed and used on readthedocs.
