### ISSUE TITLE
getFreeStreamResidual method changes functionals for viscous equation types

### ISSUE THREAD

**Issue by joanibal** [mdolab/adflow#44]
## Type of issue
What types of issue is it?
This is a bug  

## Description
The pyADFlow function `getFreestreamRes` is causing a state change for viscous equation types ('laminar ns', 'rans'). 

This is a problem since many of our old regression test use the helper function standard test, which calls `getFreestreamRes` and then evaluates the functionals. 
This means that functional values is some reference files are wrong.

### Steps to reproduce issue

call evalFuntions
call getFreestreamRes
call evalFunctions # this will give you a different answer 

see [runscript](https://gist.github.com/joanibal/1daf08fb4738f52fee122afb0feb6e5d)
…

### Expected behavior
…

call evalFuntions
call getFreestreamRes
call evalFunctions # this will give you the same answer 

### Code version (if relevant)
**Python version:** … 2.7

**External dependencies:** …

**Internal packages:** …
ADFlow 2.1.0

**Comment by shamsheersc19** [comment]
@joanibal Any updates on this?
