### ISSUE TITLE
Inlet mass flow rate BC

### ISSUE THREAD

**Issue by shlomyshitrit** [mdolab/adflow#66]
Hi,
I'm trying to define an inflow mass flow rate by using BCInflowSubsonic, namely: defining the denity and velocity magnitude.
The cgns file passed the internal checks through cgnview feature, but ADFLOW fails with a massage: "Not enough parameters for INFLOW boundary..."
Is there any other way to implement mass flow rate boundary condition? maybe by BCMassBleedInflow?

Thanks for your help,

Shlomy

## Type of issue
What types of issue is it?
_Select the appropriate type(s) that describe this issue_

- Bugfix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (non-backwards-compatible fix or feature)
- Documentation update
- Other (please describe)

## Description
A description of the issue.
### Steps to reproduce issue
1. …
2. …
3. …

### Current behavior
…

### Expected behavior
…

### Code version (if relevant)
**Python version:** …

**External dependencies:** …

**Internal packages:** …

**Comment by joanibal** [comment]
Unfortunately, in ADflow the only currently supported way to set Subsonic Inflow BCs is using total conditions. 

https://github.com/mdolab/adflow/blob/b8cb700697c44190ad1f35666a050575343638b9/src/bcdata/BCData.F90#L559-L580
