### ISSUE TITLE
Computer freezes when running simple script in parallel 

### ISSUE THREAD

**Issue by joanibal** [mdolab/adflow#73]
## Type of issue
What types of issue is it?
- Bug

## Description
This was discovered when trying to run test_18 in the new testing framework on multiple cores. For some reason it will freeze my compute (a shuttle box) when running with multiple cores, but will run fine on a single core. 

### Steps to reproduce issue
1. save the runscript below 
2. copy `conic_conv_nozzle.cgns` from adflow tests input dir to dir of runscript or modify `girdfile` option to point to that file
2. use mpirun -np 2 python freeze.py

```python
# built-ins
import unittest
import numpy as np
import os
import sys
import copy


# MACH
from baseclasses import  AeroProblem
from adflow import ADFLOW


                            
ap = AeroProblem(name='conic_conv_nozzle', alpha=90.0, mach=0.5, altitude=0.0,
                 areaRef=1.0, chordRef=1.0, R=287.87,
                            )



aero_options = {
    'gridfile':'conic_conv_nozzle.cgns',
    'outputdirectory':'./',

    # Physics Parameters
    'equationType':'euler',
    'smoother':'dadi',
    'nsubiter':3,

    'CFL':4.0,
    'MGCycle':'sg',
    'MGStartLevel':-1,

    'nCycles':1000,

    'monitorvariables':['cpu', 'resrho','cl','cd'],
    'volumevariables':['blank'],
    # 'surfacevariables':['mach', 'cp', 'vx', 'vy','vz', 'blank'],


    'useNKSolver':True,
    'nkswitchtol':.01,
    'nkjacobianlag':5,
    'nkouterpreconits':3,
    'nkinnerpreconits':2,
    'nkcfl0':1e10,
    # Convergence Parameters
    'L2Convergence':1e-10,


}


CFDSolver = ADFLOW(options=aero_options, debug=False)

CFDSolver(ap)

```

### Current behavior
Typically computer freezes before iterations complete. This sometimes will happen on the second run with some different options. 

### Expected behavior
Program exits without locking up my computer. 

### Code version (if relevant)
**Python version:** …
3.7.7
**External dependencies:** …
Petsc=3.11.0
OpenMPI=3.1.4

**Internal packages:** …
Adflow 2.2.0 - master

**Comment by shamsheersc19** [comment]
Maybe something to do with the TurboBoost? You've checked that it's disabled right?

**Comment by joanibal** [comment]
I have not. In fact, I have no clue what that is.

**Comment by shamsheersc19** [comment]
Esc (to enter setup during boot) > Advanced > CPU Configuration > Turbo Mode > Disable it.

I don't know if you're using the same hardware as my shuttle, but this was an issue for a few of us.

**Comment by joanibal** [comment]
That fixed it!

Thanks a ton Sham.

**Comment by marcomangano** [comment]
This is actually a very interesting tip that should not be missed @shamsheersc19, where shall we add this in the documentation?

**Comment by shamsheersc19** [comment]
@marcomangano Maybe with the stuff you put together for setting up computers? This issue seems to be related to the particular hardware we used to build the shuttles.

**Comment by marcomangano** [comment]
Sounds good. I am opening an issue just to keep track of this, I think that a `hardware settings` page would be valuable.

**Comment by eirikurj** [comment]
@shamsheersc19 is on point here. As mentioned this is more related to the hardware found in the Shuttle boxes. I thought we had switched this off for most of the Shuttle computers since many of them had this exact issue. @joanibal I though this had been done on the one you have, and I am surprised this is showing up now. Its possible that you have a dead CMOS battery, which then resets the BIOS to the default `Enabled` option whenever the computer is unplugged for some time.
