### ISSUE TITLE
Which papers to cite

### ISSUE THREAD

**Issue by shamsheersc19** [mdolab/adflow#78]
## Type of issue
What types of issue is it?
- Documentation update

## Description
- It's currently unclear which papers to cite. Should all 3 in the readme be cited? Is the choice left up to the user? ("Please cite ADflow in any publication for which you find it useful." in the readme)
- Also need to add https://arc.aiaa.org/doi/10.2514/6.2017-0357 for those using overset meshes.

**Comment by nwu63** [comment]
Related issue: mdolab/MACH-Aero#4

**Comment by jrram** [comment]
Done. Let me know if you suggest any modifications.
