### ISSUE TITLE
Verification and validation

### ISSUE THREAD

**Issue by shamsheersc19** [mdolab/adflow#80]
## Type of issue
Documentation update

## Description
Document where verification and validation results and cases can be found for ADflow.
- Currently unclear what has been verified and validated and what hasn't.
- This makes it challenging to explain discrepencies, troubleshoot, and maintain trust in the long term.
- 2-D & 3-D
- Equations types (Euler, laminar NS, RANS)
- Turbulence models
- Overset cases
- Rotating reference frames
- Actuator zones
- etc.

**Comment by sseraj** [comment]
I have been referring to [this paper](https://arc.aiaa.org/doi/10.2514/1.C034486) (particularly Fig. 8) for verification and some validation.
This is for RANS with multiblock and overset meshes.

**Comment by shamsheersc19** [comment]
Hydrofoil
https://www.sciencedirect.com/science/article/pii/S0889974617307934?via%3Dihub

Actuator zone test
https://github.com/joanibal/adflow/blob/master/tests/unit_tests/test_actuators.py

**Comment by marcomangano** [comment]
See section [4.1 of my paper](http://www.umich.edu/~mdolaboratory/pdf/Mangano2020a.pdf) for the 2D minimum drag shape recovery example, and the high-level verification with the paper by Palaniappan and Jameson

**Comment by eirikurj** [comment]
Time-accurate analysis, comparing to experimental and computational data.
https://arc.aiaa.org/doi/10.2514/6.2016-3121

**Comment by anilyil** [comment]
Seems like @DavidAnderegg also added a few comparisons with other well-established solvers using the M6 wing here: https://github.com/mdolab/MACH-Aero/blob/2a17dc93f0d2ddfa779ee78e1105a56a71026a62/machAeroTutorials/overset_analysis.rst Once this PR is merged (https://github.com/mdolab/MACH-Aero/pull/23) this will be in the public MACH-Aero tutorial.

**Comment by marcomangano** [comment]
@awccopp do you have any update on this?
