### ISSUE TITLE
Out of date testing instructions in the docs.

### ISSUE THREAD

**Issue by marcomangano** [mdolab/adflow#87]
## Description
As for title, the testing instructions are out of date. We moved to `testflo` but the online docs are still suggesting the `run_reg_tests.py` approach.
We should probably release a new tag for ADflow itself?

### Steps to reproduce issue
See [the docs page](https://mdolab-adflow.readthedocs-hosted.com/en/latest/install.html)

### Current behavior
Still illustrates the old `reg_tests` approach

### Expected behavior
Update with the info from the [Readme](https://github.com/mdolab/adflow/tree/master/tests)

### Code versions
The latest version (Untagged changes after v2.2.1)

**Comment by nwu63** [comment]
One more thing, we probably want to release a tagged version after this is addressed.

**Comment by marcomangano** [comment]
Agreed, once #89 is merged and this is fixed I would go for a new release
