### ISSUE TITLE
Missing `parameterized` module from dependencies

### ISSUE THREAD

**Issue by marcomangano** [mdolab/adflow#88]
## Description
With the overhauling of the testing infrastructure, it seems like we missed to include `parameterized` as a required package.
If you don't have it already installed, some of the tests will fail due to the import error (only some tests are affected, see below).
It's an easy fix, I document it for sake of completeness.

### Steps to reproduce issue
If you don't have `parameterized` available, just run `testflo` regularly.

### Current behavior
you will get this in the terminal output:
```
The following tests failed:
test_adjoint.py:../tests/reg_tests/test_adjoint.py
test_functionals.py:../tests/reg_tests/test_functionals.py
test_solve.py:../tests/reg_tests/test_solve.py
```
Looking at the error messages, they are all related to this import error

### Expected behavior
All the tests should succeed.
If you manually `pip install parameterized`, the bug is fixed.

I recommend to include `parameterized` in the `install_requires` to avoid any future issues.

### Code versions

- Python 3.8
- Testflo 1.4.2
- ADflow 2.2.1

**Comment by nwu63** [comment]
I'll work on this. The proper way to do this is to add it to an optional dependency, like what we did with `pygeo` [here](https://github.com/mdolab/pygeo/pull/47/commits/d620d322698ddd7e1dd23a838db763474cc9867c).
