### ISSUE TITLE
Format the code

### ISSUE THREAD

**Issue by nwu63** [mdolab/adflow#98]
# Description
Once @marcomangano finishes the PR on rotating frames, the python code needs to be formatted and all linting errors fixed.

**Comment by anilyil** [comment]
When formatting, we should also pay attention to the doscstring formatting. See: https://github.com/mdolab/adflow/pull/118#discussion_r598312501 Apparently we will need to remove the space before the colon in the parameter descriptions.

**Comment by nwu63** [comment]
Now that #118 is merged I think we can go ahead with the formatting right @sseraj?

**Comment by sseraj** [comment]
Yes, I will do that ASAP

**Comment by anilyil** [comment]
I will make a release before we merge that PR with the complex solver + actuator region stuff. I think formatting fixes can be a patch?

**Comment by sseraj** [comment]
> I will make a release before we merge that PR with the complex solver + actuator region stuff. I think formatting fixes can be a patch?

That would be great. No need to wait for the formatting I think. We can make a patch release if we want afterwards like you said.

**Comment by anilyil** [comment]
Okay, v2.5.0 is up. Feel free to go ahead with these changes.
